services:
  wordpress:
    image: bitnami/wordpress:6
    environment:
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DATABASE_USER}
      WORDPRESS_DATABASE_HOST: ${WORDPRESS_DATABASE_HOST}
      WORDPRESS_DATABASE_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DATABASE_PORT_NUMBER: ${WORDPRESS_DATABASE_PORT_NUMBER}
      WORDPRESS_DATABASE_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_EXTRA_WP_CONFIG_CONTENT: |
        /* redis-cache config */
        define('WP_REDIS_HOST', '${WP_REDIS_HOST}');
        define('WP_REDIS_PORT', '${WP_REDIS_PORT}');
        define('WP_REDIS_PASSWORD', '${WP_REDIS_PASSWORD}');
    volumes:
      - "wordpress:/bitnami/wordpress"
    deploy:
      mode: replicated
      replicas: 2

  mariadb:
    image: bitnami/mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb:/bitnami/mariadb

  redis:
    image: bitnami/redis
    environment:
      REDIS_PASSWORD: ${WP_REDIS_PASSWORD}

  proxy:
    image: bitnami/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./my_server_block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress.conf
      - ./wp-config.php:/opt/bitnami/wordpress/wp-config.php

volumes:
  mariadb: {}
  wordpress: {}
